[global]
type=global
user_agent=SBC-Core
default_realm=itsp.local

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=200.141.5.142
external_signaling_address=200.141.5.142

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_media_address=200.141.5.142
external_signaling_address=200.141.5.142

[proveedor1-reg]
type=registration
transport=transport-udp
outbound_auth=proveedor1-auth
server_uri=REDACTED
client_uri=REDACTED
retry_interval=60
expiration=3600
line=yes
endpoint=proveedor1

[proveedor1-auth]
type=auth
auth_type=userpass
username=REDACTED
password=REDACTED

[proveedor1-aor]
type=aor
contact=REDACTED
qualify_frequency=60

[proveedor1]
type=endpoint
transport=transport-udp
context=from-provider
disallow=all
allow=ulaw
aors=proveedor1-aor
outbound_auth=proveedor1-auth
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[proveedor1-identify]
type=identify
endpoint=proveedor1
match=REDACTED

[elevenlabs]
type=endpoint
transport=transport-tcp
context=from-client-elevenlabs
disallow=all
allow=ulaw
media_encryption=sdes
media_encryption_optimistic=yes
use_avpf=no
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[elevenlabs-aor]
type=aor
max_contacts=10
qualify_frequency=0

[elevenlabs-identify]
type=identify
endpoint=elevenlabs
match=REDACTED





[proveedor-mx]
type=endpoint
transport=transport-udp
context=from-provider-mexico
disallow=all
allow=ulaw
aors=proveedor1-aor
outbound_auth=proveedor1-auth
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
send_pai=yes
from_user=REDACTED
callerid_privacy=allowed_not_screened
trust_id_outbound=yes

[proveedor-nepal]
type=endpoint
transport=transport-udp
context=from-provider-nepal
disallow=all
allow=ulaw
aors=proveedor1-aor
outbound_auth=proveedor1-auth
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
send_pai=yes
from_user=REDACTED
callerid_privacy=allowed_not_screened
trust_id_outbound=yes
#include landmark-extensions-pjsip.conf
#include stringee-test-pjsip.conf

