# =====================================================================
#  /etc/fail2ban/filter.d/asterisk-security.conf
#  Detecta intentos de autenticacion fallidos e invitaciones a
#  peticiones no identificadas en el "security log" de Asterisk (PJSIP).
# =====================================================================
[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk

failregex = ^%(__prefix_line)s.*SecurityEvent="(FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword|UnexpectedAddress|SessionLimit)".*RemoteAddress="[^/]+/[^/]+/<HOST>/\d+".*$
            ^%(__prefix_line)s.*SecurityEvent="(FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword|UnexpectedAddress)".*RemoteAddress=".*<HOST>.*".*$

ignoreregex =
