[globals]
LCR_DEFAULT=proveedor1

[from-client-elevenlabs]
exten => _+52XXXXXXXXXX,1,NoOp(== Salida Mexico ==)
 same => n,Set(CDR(accountcode)=MX)
 same => n,MixMonitor(/tmp/test-${UNIQUEID}.wav,b)
 same => n,Dial(PJSIP/${EXTEN}@proveedor-mx,60)
 same => n,Hangup()

exten => _+977XXXXXXXXXX,1,NoOp(== Salida Nepal ==)
 same => n,Set(CDR(accountcode)=NP)
 same => n,MixMonitor(/tmp/test-${UNIQUEID}.wav,b)
 same => n,Set(NEPAL_NUMBER=${EXTEN:1})
 same => n,Dial(PJSIP/${NEPAL_NUMBER}@proveedor1,60)
 same => n,Hangup()

exten => _+91XXXXXXXXXX,1,NoOp(== Salida India ==)
 same => n,Set(CDR(accountcode)=IN)
 same => n,MixMonitor(/tmp/test-${UNIQUEID}.wav,b)
 same => n,Dial(PJSIP/${EXTEN}@proveedor1,60)
 same => n,Hangup()

exten => _.,1,NoOp(== Rechazado: no es +52/+91/+977 ==)
 same => n,Hangup()

[from-provider]
exten => _.,1,NoOp(== Entrante desde proveedor ==)
 same => n,Hangup()

[from-provider-mexico]
; vacio

[outbound-mexico]
exten => _+52XXXXXXXXXX,1,NoOp(Llamada saliente Mexico)
 same => n,Dial(PJSIP/${EXTEN}@proveedor-mx,60)
 same => n,Hangup()

#include landmark-extensions-dialplan.conf
#include stringee-test-dialplan.conf
